apiVersion: v1
items:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: hello-world
    name: hello-world
  spec:
    replicas: 1
    selector:
      app: hello-world
      deploymentconfig: hello-world
    strategy:
      resources: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: hello-world
          deploymentconfig: hello-world
      spec:
        containers:
        - image: image-registry.openshift-image-registry.svc:5000/cdj-dev/hello-world:latest
          name: hello-world
          ports:
          - containerPort: 1337
            protocol: TCP
          resources: {}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - hello-world
        from:
          kind: ImageStreamTag
          name: hello-world:${VERSION}
          namespace: cdj-dev
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: hello-world
    name: hello-world
  spec:
    ports:
    - name: 1337-tcp
      port: 1337
      protocol: TCP
      targetPort: 1337
    selector:
      app: hello-world
      deploymentconfig: hello-world
  status:
    loadBalancer: {}
kind: List
metadata: {}
parameters:
- name: VERSION
  description: Version of deploy
  required: true
  value: latest
