apiVersion: v1
kind: Template
labels:
  template: hello-world-build
metadata:
  name: hello-world-build
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      application: node-hw
    name: node-hw
  spec:
    dockerImageRepostitory: ${NODEJS_IMAGE}:${VERSION}
    lookupPolicy:
      local: false
    tags:
      - annotations: null
        name: latest
        from:
          kind: DockerImage
          name: ${NODEJS_IMAGE}:${VERSION}
      - annotations: null
        name: ${VERSION}
        from:
          kind: DockerImage
          name: ${NODEJS_IMAGE}:${VERSION}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${APPLICATION_NAME}:latest
    source:
      type: Binary
    strategy:
      dockerStrategy:
        forcePull: true
        from:
          kind: ImageStreamTag
          name: node-hw:${VERSION}
        dockerfilePath: Dockerfile
        noCache: true
      type: Source
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}-pipeline
  spec:
    source:
      git:
        uri: ${SOURCE_URL}
        ref: ${SOURCE_REF}
      sourceSecret:
        name: git-secret
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfilePath: Jenkinsfile
        env:
          - name: APPLICATION_NAME
            value: ${APPLICATION_NAME}
    triggers:
    - github:
        secret: "git-secret"
      type: GitHub
parameters:
- description: The name for the application.
  name: APPLICATION_NAME
  required: true
  value: tasks
- description: Git source URI for application
  name: SOURCE_URL
  required: true
  value: https://github.com/carnsds-ibm/hello-world
- description: Git branch/tag reference
  name: SOURCE_REF
  value: master
- description: Node JS Image Name -
  name: NODEJS_IMAGE
  required: true
  value: node
- description: Node JS Image Version -
  name: VERSION
  required: true
  value: latest
